### ISSUE TITLE
Not all options are configurable in Helm Chart

### ISSUE THREAD

**Issue by aluo-at-tyro** [hjacobs/kube-downscaler#62]
Only interval, namespace and debug are configurable in the current helm chart, while more  command line options are available. It would be grateful if all command line options are supported in the helm chart.

**Comment by hjacobs** [comment]
Feel free to provide a PR, I'm not really using nor maintaining the Helm Chart myself.

**Comment by guikcd** [comment]
Maybe it's better to use environment variables anywhere (https://github.com/hjacobs/kube-downscaler/blob/master/kube_downscaler/cmd.py#L16-L93; missing ones are less than used ones) so that it is easy to handle them ? The idea is to define a `env` array in values.yml to define each variable (but all parameters need to read a corresponding environment variable.

So that `helm-chart/templates/deployment.yaml` will looks like (from this example: https://github.com/helm/charts/tree/master/stable/cerebro]:
```
[...]
    spec:
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "kube-downscaler.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      containers:
      - name: {{ template "kube-downscaler.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- if .Values.env }}
        env:
          {{- range $index, $element := .Values.env }}
          - name: {{ $index | quote }}
            value: {{ $element | quote }}
          {{- end }}
          {{- end }}
[...]
```

And `values.yaml`:
```
env:
  GRACE_PERIOD: "1800"
  EXCLUDE_NAMESPACES: kube-system,mynamespace
[...]
```

Integer need to be written in string form (https://helm.sh/docs/howto/charts_tips_and_tricks/), but i don't think this will be a problem...

What do you think ? I can propose the PR for the python code and the helm chart.

**Comment by hjacobs** [comment]
I'm no longer supporting the Helm chart in this repo, see #108.
